# Functions for pre-processing ascents data.

# Copyright 2019 Dean Scarff
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

library(dplyr)
library(stringr)


# Converts an ascent type like "Hang dog" to a code like "dog".  The codes
# are all lower-case and contain no spaces.
NormalizeAscentType <- function(ascent_type) {
  ascent_type %>%
    str_to_lower() %>%
    str_remove_all(fixed(" ")) %>%
    recode(hangdog = "dog")
}

# Reads a CSV export of a climber's logbook from theCrag.  The filename is
# assumed to be in the format generated by theCrag, i.e.
# "climbername-logbook-YYYY-MM-DD.csv".
# Returns a "raw ascents" data frame with columns "ascentId", "route",
# "climber", "tick", "grade" and "timestamp".
ReadLogbook <- function(filename) {
  m <- str_match(basename(filename), "([^-]+)-logbook-\\d{4}-\\d{2}-\\d{2}")
  climber <- str_to_lower(m[[1, 2]])
  df <- read.csv(
    filename,
    # R doesn't support 64-bit integers, so force IDs to be interpreted as characters.
    colClasses = c(Ascent.ID = "character", Route.ID = "character"),
    stringsAsFactors = FALSE
  )
  df %>%
    select(Ascent.ID, Ascent.Type, Route.ID, Route.Grade, Ascent.Date) %>%
    mutate(
      route = factor(Route.ID),
      climber = climber,
      tick = factor(NormalizeAscentType(Ascent.Type)),
      grade = as.integer(Route.Grade),
      timestamp = as.integer(
        as.POSIXct(Ascent.Date, format = "%FT%H:%M:%SZ", optional = TRUE)
      )
    ) %>%
    na.omit() %>%
    select(ascentId = Ascent.ID, route, climber, tick, grade, timestamp)
}

# Reads all logbooks in directory "dir".  Logbook filenames are assumed to be
# in the format generated by theCrag, i.e. "climbername-logbook-YYYY-MM-DD.csv".
# Returns a "raw ascents" data frame with columns "ascentId", "route",
# "climber", "tick", "grade" and "timestamp".
ReadLogbooks <- function(dir) {
  logbooks <- Sys.glob(file.path(dir, "*-logbook-*.csv"))
  dfs <- purrr::map(logbooks, ReadLogbook)
  bind_rows(dfs)
}

# Classifies tick types like "dog" into either 1 (clean), 0 (not clean) or NA.
# Note that we are optimistic about tick types that are ambiguous in practice,
# e.g. a plain "tick" is dropped.
# Also note that no tick shift is applied - a clean top rope ascent is
# equivalent to an onsight.
IsTickClean <- function(ticktype) {
  # See https://www.thecrag.com/en/article/ticktypes
  case_when(
    ticktype %in% c(
      "onsight", "flash", "redpoint", "groundupredpoint",
      "pinkpoint", "clean", "onsightsolo", "topropeonsight", "topropeflash",
      "topropeclean", "secondclean", "leadsolo", "firstfreeascent",
      "tick", "second"
    ) ~ 1,
    ticktype %in% c(
      "dog", "attempt", "retreat", "working",
      "allfreewithrest", "toproperest", "ghost", "secondrest"
    ) ~ 0
  )
}

# Given a data frame containing "raw" ascents, normalizes these to ascent,
# page and route tables.
#
# df_raw is expected to have the columns "ascentId", "route", "climber",
# "tick", "grade", "timestamp".
#
# period_length is the number of seconds per page.
NormalizeTables <- function(df_raw, period_length) {
  df <- df_raw %>%
    mutate(clean = IsTickClean(tick)) %>%
    filter(!is.na(clean)) %>%
    filter(!is.na(grade)) %>%
    mutate(route = droplevels(route), climber = droplevels(climber))

  # Summarize the tick counts.
  cat(
    nrow(df), "ascents by",
    nlevels(df$climber), "climbers over",
    nlevels(df$route), "routes;",
    sprintf("%0.2f%%", mean(df$clean) * 100.0), "clean ascents\n"
  )

  # Find the most popular routes:
  top_routes <- count(df, route, sort = TRUE)

  # Make the route with the most ascents the "first" route.  This means it will
  # be used as the reference route (rating of 1).  Having lots of ascents
  # means it is (hopefully) a good reference point for comparing climbers.
  df$route <- relevel(df$route, ref = as.character(top_routes[[1, 1]]))

  df_routes <- df %>%
    group_by(route) %>%
    summarise(ewbank = floor(median(grade)))

  df_ascents <- df %>%
    mutate(t = (timestamp - min(df$timestamp)) %/% period_length) %>%
    arrange(climber, t)

  df_pages <- df_ascents %>%
    group_by(climber, t) %>%
    summarise()
  # Set first_page[c] to be the index in df_pages of the first page for climber
  # c.
  first_page <- (df_pages %>% group_by(climber) %>% summarise(n = n()) %>%
    mutate(idx = head(cumsum(c(1, n)), -1)))$idx

  # time relative to the first ascent from the same climber
  df_pages$rel_t <- df_pages$t - df_pages$t[first_page[df_pages$climber]]
  # time relative to the next page for the same climber (meaningless for last
  # page of each climber).
  df_pages$gap <- c(diff(df_pages$rel_t), 0)

  df_pages <- df_pages %>%
    select(climber, t, gap) %>%
    ungroup() %>%
    mutate(page = row_number())

  df_ascents <- df_ascents %>%
    inner_join(df_pages, by = c("climber", "t")) %>%
    select("route", "climber", "clean", "page")

  df_ascents <- tibble::as_tibble(df_ascents)

  list(ascents = df_ascents, pages = df_pages, routes = df_routes)
}

# Writes normalized tables to CSV files.
#
# The files are written with standard names to the directory specified by
# "dir".
#
# "dfs" should be a list of data frames, with the tags "ascents", "routes" and
# "pages"; like what NormalizeTables returns.
WriteNormalizedTables <- function(dfs, dir) {
  write.csv(dfs$ascents %>%
    mutate(route = as.integer(route) - 1, page = page - 1) %>%
    select(-climber),
  file.path(dir, "ascents.csv"),
  row.names = FALSE
  )
  write.csv(dfs$routes %>%
    mutate(grade = pmax(1, 1 + ewbank - ewbank[[1]])) %>%
    select(-ewbank),
  file.path(dir, "routes.csv"),
  row.names = FALSE
  )
  write.csv(dfs$pages %>%
    select(climber, gap) %>%
    mutate(climber = as.integer(climber) - 1),
  file.path(dir, "pages.csv"),
  row.names = FALSE
  )
}
