# Functions for reading ascents from theCrag's CSV logbook exports.

# Copyright Contributors to the Climbing Ratings project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#' Reads a CSV export of a climber's logbook from theCrag.
#'
#' @param df data frame with the same columns as CSV logbooks from theCrag.
#' @param climber character username to populate the "climber" column in the
#' returned data frame.
#' @return a "raw ascents" data frame with columns "ascentId", "route",
#' "climber", "tick", "grade", and "timestamp".
.ParseLogbook <- function(df, climber) {
  df %>%
    dplyr::transmute(
      ascentId = .data$Ascent.ID,
      route = .data$Route.ID,
      climber = climber,
      tick = NormalizeAscentType(.data$Ascent.Type),
      grade = suppressWarnings(as.integer(.data$Route.Grade)),
      timestamp = .data$Ascent.Date %>%
        as.POSIXct(format = "%FT%H:%M:%SZ", optional = TRUE, tz = "UTC") %>%
        as.integer()
    ) %>%
    tidyr::drop_na()
}

#' Reads a CSV export of a climber's logbook from theCrag.
#'
#' @param filename path to file, assumed to be in the format generated by
#' theCrag, i.e. "climber-logbook-YYYY-MM-DD.csv".
#' @return a "raw ascents" data frame with columns "ascentId", "route",
#' "climber", "tick", "grade", and "timestamp".
ReadLogbook <- function(filename) {
  m <- stringr::str_match(
    basename(filename),
    "([^-]+)-logbook-\\d{4}-\\d{2}-\\d{2}"
  )
  utils::read.csv(
    filename,
    # R doesn't support 64-bit integers, so force IDs to be interpreted as characters.
    colClasses = c(Ascent.ID = "character", Route.ID = "character"),
    stringsAsFactors = FALSE
  ) %>%
    .ParseLogbook(climber = stringr::str_to_lower(m[[1, 2]]))
}

#' Reads all logbooks in a directory.  Logbook filenames are assumed to be
#' in the format generated by theCrag, i.e. "climber-logbook-YYYY-MM-DD.csv".
#'
#' @param dir the directory containing logbook files to read.
#' @return a "raw ascents" data frame with columns "ascentId", "route",
#' "climber", "tick", "grade" and "timestamp".
ReadLogbooks <- function(dir) {
  logbooks <- Sys.glob(file.path(dir, "*-logbook-*.csv"))
  dfs <- purrr::map(logbooks, ReadLogbook)
  dplyr::bind_rows(dfs)
}
