# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts the list-of-singleton-integer-vector structures typical of
#' jsonlite to an atomic vector of integers.  NULLs are converted to NA.
#'
#' @param lst a list of lists of characters
#' @param idx the singleton element of the inner list (1-based) to extract
#' @keywords internal
FlattenInt <- function(lst, idx = 1L) {
    .Call('_climbr_FlattenInt', PACKAGE = 'climbr', lst, idx)
}

#' Converts the list-of-singleton-character-vector structures typical of
#' jsonlite to an atomic vector of characters.  NULLs are converted to NA.
#'
#' @param lst a list of lists of characters
#' @param idx the singleton element of the inner list (1-based) to extract
#' @keywords internal
FlattenChr <- function(lst, idx = 1L) {
    .Call('_climbr_FlattenChr', PACKAGE = 'climbr', lst, idx)
}

